version: '3'

services:
  compress:
    image: macmvak/compress_ph_bot
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 40

