version: '3'

services:
  compress:
    image: macmvak/compress_ph_bot:latest
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 40 --cleanup
    environment:
      REPO_USER: "${REPO_USER}"
      REPO_PASS: "${REPO_PASSWORD}"
