# This is a basic workflow to help you get started with Actions

name: deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    name: Publish the package
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Docker Image CI'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10000
      - name: Write word
        run: echo "I love Telegram."
