name: main_test


on: [create, release, push]


jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    name: Python And Docker Test
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build .
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies #check correctness of dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 .
